POST http://localhost:15672/api/exchanges/%2F/warehouse-events-topic/
    publishAuthorization: Basic bXl1c2VyOm15cGFzc3dvcmQ= #echo -n 'myuser:mypassword' |
    base64Content-Type: application/json
    {  "properties": {},  "routing_key": "incoming.deliveries.weighted",
    "payload":
    "{\
    "warehouseId\":\"7b5790d2-51f0-4003-aecf-41c9a4552633\",
    \"sellerId\":\"7b5790d2-51f0-4003-aecf-41c9a4552633\",
    \"deliveryId\":\"7b5790d2-51f0-4003-aecf-41c9a4552633\",
    \"materialType\":\"PT\",\"weight\":\"50\"}",
    "payload_encoding": "string"
    }