POST http://localhost:8180/realms/mineral/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=frontend&client_secret=exBMuPxIaEnnmQwoJUiEUMlAjdPccOHf&username=john_smith&password=password&grant_type=password&scope=openid

> {%
    client.global.set("access_token", response.body.access_token)
%}

###

POST http://localhost:8090/api/appointments
Content-Type: application/json
Accept:application/json
Authorization: Bearer {{access_token}}

{
  "timeSlot":  "2024-11-01 19:30:34",
  "truckLicensePlate":  "kd-kldfjkd-klk",
  "amountTons":  10.0,
  "material": "CEMENT",
  "sellerName": "test_seller1"
}





###
PATCH http://localhost:8090/api/appointments/kd-kldfjkd-klk
Content-Type: application/json
Accept:application/json


###
POST http://localhost:8090/api/weighbridges/kd-kldfjkd-klk/wbt
Content-Type: application/json
Accept: application/json

{
  "truckInitialWeightTons":  10.0
}


###
PATCH http://localhost:8090/api/weighbridges/kd-kldfjkd-klk/wbt
Content-Type: application/json
Accept: application/json

{
  "truckFinalWeightTons":  5.0
}

###
GET http://localhost:8090/api/unavailable-appointment-dates
Accept: application/json
Authorization: Bearer {{access_token}}



###
GET http://localhost:8090/api/warehouses/57f7f2a0-6928-4fe8-9bb8-afc36915929f/contents
Accept: application/json
Authorization: Bearer {{access_token}}