server:
  port: ${PORT:8090}
  servlet:
    context-path: /api

logging:
  level:
    org:
      springframework:
        security: DEBUG

spring:
  config:
    additional-location: ${SPRING_CONFIG_ADDITIONAL_LOCATION}
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    initialization-mode: always
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/app_db}
    username: ${DATASOURCE_USER:user}
    password: ${DATASOURCE_PASS:password}
    MYSQL_ROOT_PASSWORD: password
  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: mypassword
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/mineral/protocol/openid-connect/certs
          issuer-uri: http://localhost:8180/realms/mineral



